### ISSUE TITLE
OpenGL Renderer

### ISSUE THREAD

**Issue by Xottab-DUTY** [Xottab-DUTY/xray-16#3]
Unfinished and broken. Fix!

**Comment by hpl1nk** [comment]
//Fix me!

**Comment by eagleivg** [comment]
Вот хотелось бы, но я в этом совсем не шарю. А давай лучше вулкан запилим, поглядим на DXVK и по образу и подобию?

**Comment by Xottab-DUTY** [comment]
@eagleivg вполне возможно =)
